version: '3'

networks:
  prodnetwork:
    driver: bridge

volumes:
  nexus-data:
  jenkins-data:
  nginx-data:

services:
  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
    networks:
      - prodnetwork
    volumes:
      - nginx-data:/etc/nginx
      - /etc/localtime:/etc/localtime:ro
  nexus:
    build: ./nexus
    restart: always
    ports:
      - "18081:8081"
    networks:
      - prodnetwork
    volumes:
      - nexus-data:/nexus-data
    depends_on:
      - nginx
  jenkins:
    build: ./jenkins
    command: --prefix="/jenkins"
    restart: always
    ports:
      - "18080:8080"
    networks:
      - prodnetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins-data:/var/lib/jenkins/
    depends_on:
      - nginx
      - nexus
    environment:
      - NEXUS_PORT=8081
      - SONAR_PORT=9000
      - SONAR_DB_PORT=5432
